[supervisord]
nodaemon=true
user=root
# Лог самого супервизора (в консоль докера)
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

# --- FASTAPI ---
[program:fastapi]
command=uvicorn main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
# Вывод напрямую в stdout контейнера
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

# --- ENGINE ---
[program:engine]
command=python engine_worker.py
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

# --- CONNECTOR ---
[program:connector]
command=python connector_worker.py
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

# --- TG BOT ---
[program:tg_bot]
command=python tg_worker.py
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

# --- SCHEDULER ---
[program:scheduler]
command=python scheduler.py
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0