[supervisord]
nodaemon=true
user=root
# Основной лог самого супервизора
logfile=/app/logs/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
pidfile=/var/run/supervisord.pid

# --- FASTAPI ---
[program:fastapi]
command=uvicorn main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/logs/fastapi.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

# --- ENGINE ---
[program:engine]
command=python engine_worker.py
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/logs/engine.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

# --- CONNECTOR ---
[program:connector]
command=python connector_worker.py
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/logs/connector.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

# --- TG BOT ---
[program:tg_bot]
command=python tg_worker.py
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/logs/tg_worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

# --- SCHEDULER ---
[program:scheduler]
command=python scheduler.py
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/app/logs/scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5